#include <metadata/plugins.h>
#include <metadata/ports.h>
#include <metadata/developers.h>

using namespace lsp;

static const port_t midi_edit_ports[] =
{
    PORTS_MIDI_CHANNEL,
    INT_CONTROL("ch01_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch02_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch03_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch04_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch05_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch06_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch07_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch08_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch09_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch10_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch11_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch12_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch13_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch14_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch15_prog", "Program", /*units*/, /* Limits: 0-99 */),
    INT_CONTROL("ch16_prog", "Program", /*units*/, /* Limits: 0-99 */),
    SWITCH("ch01_prog_bypass", "Pass Through", true),
    SWITCH("ch02_prog_bypass", "Pass Through", true),
    SWITCH("ch03_prog_bypass", "Pass Through", true),
    SWITCH("ch04_prog_bypass", "Pass Through", true),
    SWITCH("ch05_prog_bypass", "Pass Through", true),
    SWITCH("ch06_prog_bypass", "Pass Through", true),
    SWITCH("ch07_prog_bypass", "Pass Through", true),
    SWITCH("ch08_prog_bypass", "Pass Through", true),
    SWITCH("ch09_prog_bypass", "Pass Through", true),
    SWITCH("ch10_prog_bypass", "Pass Through", true),
    SWITCH("ch11_prog_bypass", "Pass Through", true),
    SWITCH("ch12_prog_bypass", "Pass Through", true),
    SWITCH("ch13_prog_bypass", "Pass Through", true),
    SWITCH("ch14_prog_bypass", "Pass Through", true),
    SWITCH("ch15_prog_bypass", "Pass Through", true),
    SWITCH("ch16_prog_bypass", "Pass Through", true),

    INT_CONTROL("ch01_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch02_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch03_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch04_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch05_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch06_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch07_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch08_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch09_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch10_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch11_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch12_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch13_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch14_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch15_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch16_vel", "Velocity", /*units*/, /* Limits: 0-255 */),
    SWITCH("ch01_vel_bypass", "Pass Through", true),
    SWITCH("ch02_vel_bypass", "Pass Through", true),
    SWITCH("ch03_vel_bypass", "Pass Through", true),
    SWITCH("ch04_vel_bypass", "Pass Through", true),
    SWITCH("ch05_vel_bypass", "Pass Through", true),
    SWITCH("ch06_vel_bypass", "Pass Through", true),
    SWITCH("ch07_vel_bypass", "Pass Through", true),
    SWITCH("ch08_vel_bypass", "Pass Through", true),
    SWITCH("ch09_vel_bypass", "Pass Through", true),
    SWITCH("ch10_vel_bypass", "Pass Through", true),
    SWITCH("ch11_vel_bypass", "Pass Through", true),
    SWITCH("ch12_vel_bypass", "Pass Through", true),
    SWITCH("ch13_vel_bypass", "Pass Through", true),
    SWITCH("ch14_vel_bypass", "Pass Through", true),
    SWITCH("ch15_vel_bypass", "Pass Through", true),
    SWITCH("ch16_vel_bypass", "Pass Through", true),

    INT_CONTROL("ch01_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch02_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch03_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch04_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch05_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch06_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch07_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch08_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch09_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch10_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch11_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch12_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch13_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch14_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch15_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    INT_CONTROL("ch16_clamp", "Clamp Velocity", /*units*/, /* Limits: 0-255 */),
    SWITCH("ch01_clamp_bypass", "Enabled", false),
    SWITCH("ch02_clamp_bypass", "Enabled", false),
    SWITCH("ch03_clamp_bypass", "Enabled", false),
    SWITCH("ch04_clamp_bypass", "Enabled", false),
    SWITCH("ch05_clamp_bypass", "Enabled", false),
    SWITCH("ch06_clamp_bypass", "Enabled", false),
    SWITCH("ch07_clamp_bypass", "Enabled", false),
    SWITCH("ch08_clamp_bypass", "Enabled", false),
    SWITCH("ch09_clamp_bypass", "Enabled", false),
    SWITCH("ch10_clamp_bypass", "Enabled", false),
    SWITCH("ch11_clamp_bypass", "Enabled", false),
    SWITCH("ch12_clamp_bypass", "Enabled", false),
    SWITCH("ch13_clamp_bypass", "Enabled", false),
    SWITCH("ch14_clamp_bypass", "Enabled", false),
    SWITCH("ch15_clamp_bypass", "Enabled", false),
    SWITCH("ch16_clamp_bypass", "Enabled", false),

    INT_CONTROL("ch01_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch02_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch03_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch04_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch05_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch06_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch07_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch08_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch09_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch10_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch11_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch12_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch13_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch14_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch15_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    INT_CONTROL("ch16_vel_amp", "Amplify", /*units*/, /* Limits: -110 - +100 */),
    SWITCH("ch01_amp_before", "Before Clamp", false),
    SWITCH("ch02_amp_before", "Before Clamp", false),
    SWITCH("ch03_amp_before", "Before Clamp", false),
    SWITCH("ch04_amp_before", "Before Clamp", false),
    SWITCH("ch05_amp_before", "Before Clamp", false),
    SWITCH("ch06_amp_before", "Before Clamp", false),
    SWITCH("ch07_amp_before", "Before Clamp", false),
    SWITCH("ch08_amp_before", "Before Clamp", false),
    SWITCH("ch09_amp_before", "Before Clamp", false),
    SWITCH("ch10_amp_before", "Before Clamp", false),
    SWITCH("ch11_amp_before", "Before Clamp", false),
    SWITCH("ch12_amp_before", "Before Clamp", false),
    SWITCH("ch13_amp_before", "Before Clamp", false),
    SWITCH("ch14_amp_before", "Before Clamp", false),
    SWITCH("ch15_amp_before", "Before Clamp", false),
    SWITCH("ch16_amp_before", "Before Clamp", false)
}
